name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    env:
      MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
      MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
      MODULE_NAME: N98_Guillotine
      COMPOSER_NAME: n98/headless-guillotine
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-coding-standard@master
      - uses: docker://yireo/github-actions-magento-unit-tests:7.3
        env:
          MAGENTO_VERSION: '2.3.4'
      - uses: docker://yireo/github-actions-magento-unit-tests:7.3
        env:
          MAGENTO_VERSION: '2.3.7-p3'
      - uses: docker://yireo/github-actions-magento-unit-tests:7.4
        env:
          MAGENTO_VERSION: '2.4.3-p2'
      - uses: docker://yireo/github-actions-magento-unit-tests:8.1
        env:
          MAGENTO_VERSION: '2.4.4'
